### ISSUE TITLE
Sandbox transforms arrays to objects on the sandbox boundary

### ISSUE THREAD

**Issue by Vratislav** [superfaceai/one-sdk-js#16]
# Behavior

given profile snippet

```
usecase GetActivities {
  input {
    filterId
    userId
  }

  result {
    activities
  }
}

```

and given map snippet
```
map GetActivities {
  http GET "/api/v1/activities" {
        security apikey query {
          name = "api_token"
        }   
    request {
          query {
               filter_id = input.filterId
               user_id = input.userId
          }       
    }

    response 200 {

        map result if (body.success) {
          activities = body.data
        }

        map error if (!body.success) {}
      }
  }
}
```

`result.value.activities` contains Dictionary instead of Array (Array indicies are used as keys)

# Expected behaviour

I expected `result.value.activities` to contain array 

(But maybe I am wrong and the map implicitly dictates conversion to Dictionary in this case?)

**Comment by lukas-valenta** [comment]
This issue seems to be reintroduced in vm2: https://github.com/patriksimek/vm2/issues/198
