### ISSUE TITLE
Support nested properties when specifying location of apiKey in body

### ISSUE THREAD

**Issue by freaz** [superfaceai/one-sdk-js#176]
## Expected Behavior
I am able to specify token location in nested structure

## Current Behavior
Property with specified name is set in root of the data object.

## Possible Solution
Allow to use [JSON Pointer](https://datatracker.ietf.org/doc/html/rfc6901) to specify location.

**Comment by jnv** [comment]
I like the use of JSON Pointer which nicely covers edge cases with special characters in property names.

One point to consider is how much safe / transparent is for SDK to manipulate the payload after being prepared by map. For example, given the following payload in body:

```json
{
  "data": {
    "properties": ["foo", "bar"]
  }
}
```

And given the following pointer for `apiKey` inside `body`: `/data/properties/token`

I am trying to add property to an array, which is clearly a mistake which will result into an error during `perform` (or perhaps even by linter if we can do type checking on body of `http` call).

Other case is when the properties do not exist in the payload, e.g. I am sending either an empty body or just `{"data": {}}`. Should SDK automatically create the missing properties in the path for me? I'd say yes.

I think both of these cases are okay assuming they will be explicitly documented and provide friendly error message.
